test git commit
agiresearch/OpenAGI pull request #64
Opened 2024-05-18 22:06 UTC by TobyGE

2024-05-18 23:38 UTC, dongyuanjushi requested changes
Could you modify your commit messages to follow the format seen from https://github.com/agiresearch/AIOS/blob/main/CONTRIBUTE.md?  
To modify your commit messages, squash git messages and git commit --amend may help.

2024-05-18 23:42 UTC, TobyGE commented
does it look good to you now?

2024-05-19 00:26 UTC, dongyuanjushi commented
> does it look good to you now?

It currently change the pr message, but does not change the git commit message. 
<img width="809" alt="git commit" src="https://github.com/agiresearch/OpenAGI/assets/48231234/93c9166e-f201-4870-ab1b-ec23fd046e3c">


To modify the git commit message, you need to change it locally and re-push. You do not need to create a new pr, as the pr will be automatically updated once you push.

2024-05-27 18:37 UTC, dongyuanjushi approved these changes

2024-05-27 18:37 UTC, merged