[docs] Added READMEs in each directory
agiresearch/OpenAGI pull request #90
Opened 2024-08-01 20:12 UTC by om-raheja

This is my documentation with README.md files in each directory slightly modified. I believe running "git rebase" didn't work for me again, even though locally it appears everything is squashed. I request the maintainers to make adjustments as necessary, although I believe what I made in this hour should hold value for anyone who wants to contribute to OpenAGI itself and to improve it's further maintenance. Thanks.

2024-08-01 20:15 UTC, om-raheja commented
I see the test failed and it's because I didn't merge, but I don't have that issue locally so I'm not sure how to resolve it.

2024-08-01 20:35 UTC, dongyuanjushi commented on openagi/src/agents/native_agents/academic_agent/academic_agent.py
Could you remove the original files in the openagi/src folder? These files are deprecated due to recent code refactor.

2024-08-01 20:37 UTC, dongyuanjushi requested changes
Could you pull the latest files in the openagi and remove the deprecated files in the openagi/src and use the latest version in the pyopenagi? This is because openagi has been recently refactored. Thank you!

2024-08-01 20:40 UTC, om-raheja commented
Yeah, I had to deal with that when merging. I removed the `openagi/` directory and it should work okay now.

2024-08-01 20:56 UTC, dongyuanjushi commented on pyopenagi/agents/README.md
Could you rename the titles of all the commented README, e.g., from openagi/src to the current folder name?

2024-08-01 21:00 UTC, dongyuanjushi commented on pyopenagi/tools/offline/README.md
Could you also remove the offline and online folder, they are deprecated now? The tool folder is structured as org_name/tool_name/xxx. Online and offline are no longer used.

2024-08-01 21:01 UTC, dongyuanjushi commented on setup.py
Could you delete the setup.py? It is deprecated and pyproject.toml is currently used to build packages

2024-08-01 21:03 UTC, dongyuanjushi requested changes
Could you do the changes for some specific files/folders?

2024-08-02 23:29 UTC, dongyuanjushi commented on pyopenagi/agents/README.md
Could you remove the line 4-5 as the native_agents and agent_config folders are deprecated?

2024-08-02 23:30 UTC, dongyuanjushi commented on pyopenagi/agents/agent_factory.py
Could you remove the manual configurated self.agent_table as they are no long required? Current agent class can be dynamically loaded by calling self.load_agent_instance.

2024-08-02 23:31 UTC, dongyuanjushi commented on pyopenagi/agents/example/README.md
The title of this file remains to be changed.

2024-08-02 23:32 UTC, dongyuanjushi commented on pyopenagi/agents/example/rag_agent/README.md
The title of this file remains to be changed.

2024-08-02 23:33 UTC, dongyuanjushi requested changes
Could you do the changes mentioned above?

2024-08-04 03:55 UTC, dongyuanjushi approved these changes

2024-08-04 03:55 UTC, merged